version: 2    
updates:
  - directory: /
    package-ecosystem: nuget
    ignore:
      - dependency-name: Microsoft.CodeAnalysis.*
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily

